### ISSUE TITLE
Could I translate your post about goawk to Chinese

### ISSUE THREAD

**Issue by chinanf-boy** [benhoyt/goawk#12]
@benhoyt 

## Your Writing
https://benhoyt.com/writings/goawk/

**Comment by benhoyt** [comment]
Definitely! I'm honoured. The Markdown source is [here](https://github.com/benhoyt/benhoyt.github.com/blob/master/writings/goawk.md). Let me know once you've published it and I can add a link.

**Comment by chinanf-boy** [comment]
sure

**Comment by chinanf-boy** [comment]
@benhoyt 

`Chinese`: -- **En** -->- **Zh**  ：`中文`

### Here we go, Translation

- **1.** your git repo:`benhoyt/goawk`'s README.md + `writing/goawk` [中文](https://github.com/chinanf-boy/goawk-zh)

- **2.** your `writing/goawk` also upload my blog [yobrave](http://llever.com/2018/11/19/%E8%AF%91-goawk%E4%B8%80%E4%B8%AA%E7%94%A8go%E7%BC%96%E5%86%99%E7%9A%84awk%E8%A7%A3%E9%87%8A%E5%99%A8/)

**Comment by benhoyt** [comment]
Thank you!

**Comment by benhoyt** [comment]
I added a link to the Chinese translation at the top of https://benhoyt.com/writings/goawk/

**Comment by benhoyt** [comment]
Hi @chinanf-boy: just a note in case you want to make the update too. I made a change to how I display the performance numbers: https://benhoyt.com/writings/goawk/#performance-numbers

It's inverted, so higher is better, and I normalize it to awk instead of goawk. This makes it easier to read, and easier to compare as the GoAWK gets faster.

Change here: https://github.com/benhoyt/benhoyt.github.com/commit/40985f5bc24ad444f73ca54523f5ce81c452884a
