### ISSUE TITLE
Misleading Error When Header Name Used in BEGIN/END

### ISSUE THREAD

**Issue by cwarden** [benhoyt/goawk#238]
When `@"Header_Name"` is used in `BEGIN` and `END` blocks, the error message is misleading, e.g.

```
$ goawk --csv  -H 'BEGIN { print @"HEADER" }' /dev/null
@ only supported if header parsing enabled; use -H or add "header" to INPUTMODE
```

**Comment by benhoyt** [comment]
Good point, thanks. Do you think just a better error message would help, for example:

```
$ goawk --csv  -H 'BEGIN { print @"HEADER" }' /dev/null
no field names for @; use -H or add "header" to INPUTMODE, or use "getline" if in BEGIN
```

**Comment by cwarden** [comment]
I think just a better error would suffice.  Maybe something like `@ not supported in BEGIN/END` if headers are enabled.

Would it be too much work to make a parser error?

**Comment by benhoyt** [comment]
Yeah, I thought about that -- unfortunately you can't easily make it a parser error, as you can specify the input mode as run time, either by setting `INPUTMODE` in the `BEGIN` block, or by setting a variable with `goawk -v`. From the [examples in the docs](https://github.com/benhoyt/goawk/blob/master/docs/csv.md#example-different-ways-to-specify-csv-mode):

```
$ goawk 'BEGIN { INPUTMODE="csv header" } @"State"=="New York" { print @"Abbreviation" }' testdata/csv/states.csv
NY
$ goawk -v 'INPUTMODE=csv header' '@"State"=="New York" { print @"Abbreviation" }' testdata/csv/states.csv
NY
```

You *can* also use `@"HEADER"` in `BEGIN` if you've already read the first line manually with `getline`, for example:

```
$ echo -e 'FOO,BAR\nfoo,bar' | go run . --csv -H 'BEGIN { getline; print @"FOO" }'
foo
```

That's why the error message I've proposed is a bit more verbose. However, it shouldn't be "or use getline" it should be "and use getline":

```
$ echo -e 'FOO,BAR\nfoo,bar' | ./goawk --csv -H 'BEGIN { print @"FOO" }'
no field names for @; use -H or add "header" to INPUTMODE, and use "getline" first if in BEGIN
```
