### ISSUE TITLE
it can't work on windows?

### ISSUE THREAD

**Issue by lilixiong2018** [benhoyt/goawk#25]
I download the newest release version, and run as example (Win7/X64, under cmder):
```
$ goawk 'BEGIN { print "foo", 42 }'
---------------------------------------------------
'BEGIN
      ^
---------------------------------------------------
parse error at 1:7: didn't find end quote in string
```

```
$ echo 1 2 3 | goawk '{ print $1 + $3 }'
---------------------------------------------------
'{
  ^
---------------------------------------------------
parse error at 1:3: didn't find end quote in string
```

If I use use double-quoted instead single-quoted, it can work:
```
$ goawk "BEGIN { print "foo", 42 }"
 42

```
this result is 42, lose 'foo' ?

```
$ echo 1 2 3 | goawk "{ print $1 + $3 }"
4
```

```
$ goawk "BEGIN { print 'foo', 42 }"
foo 42
```
work ok.

IF I RUN THAT:
```
$ goawk "{print 'foo'}"
```
!!!RUN WITH ENDLESS!!!

**Comment by benhoyt** [comment]
I believe this is due to Windows shell handling quoting quite differently than POSIX. What shell are you using: cmd.exe or PowerShell or something else?

I believe Windows shells basically use double quote for quoting, so the intention is to use double quotes around the source string and single quotes within that (it's not POSIX AWK compatible, but it works better for Windows). So this way:

    $ goawk "BEGIN { print 'foo', 42 }"
    foo 42

Can you please run the attached program with all of the argument examples that you posted in your issue report and reply with what the output is for each? It's just a Windows exe that prints the command line arguments, in quoted format, one per line.

[cmdline.exe.zip](https://github.com/benhoyt/goawk/files/3141935/cmdline.exe.zip)

**Comment by benhoyt** [comment]
Other "fun" reading: http://daviddeley.com/autohotkey/parameters/parameters.htm#WIN and http://www.windowsinspired.com/understanding-the-command-line-string-and-arguments-received-by-a-windows-program/

**Comment by lilixiong2018** [comment]
I run goawk under cmder, shell is cmd.exe. In pure cmd.exe environment, the result is no different：
![Snipaste_2019-05-04_07-24-10](https://user-images.githubusercontent.com/40269098/57170184-b463a380-6e3d-11e9-83b2-db094b11d342.png)

the result of cmdline.exe:
```
D:\download\cmdline.exe>cmdline 'BEGIN { print "foo", 42 }'
"'BEGIN"
"{"
"print"
"foo,"
"42"
"}'"
```

```
D:\download\cmdline.exe>echo 1 2 3 | cmdline '{ print $1 + $3 }'
"'{"
"print"
"$1"
"+"
"$3"
"}'"
```

```
D:\download\cmdline.exe>cmdline "{print 'foo'}"
"{print 'foo'}"
```

**Comment by lilixiong2018** [comment]
If I run it under msys2/x64, the result is:
![Snipaste_2019-05-04_07-36-46](https://user-images.githubusercontent.com/40269098/57170447-841d0480-6e3f-11e9-9fe5-bfa10f0b6c83.png)

**Comment by benhoyt** [comment]
Yes, this all makes sense. You have to use `"` as the overall quoting character for Windows shell, and then `'` as the internal quote character for AWK strings (the latter is special, non-POSIX behavior supported by GoAWK for this Windows use case). So:

```
$ goawk "BEGIN { print 'foo', 42 }"
$ echo 1 2 3 | goawk "{ print $1 + $3 }"
```

And the reason that `$ goawk "{print 'foo'}"` runs without finishing is simply that it's waiting for input (from stdin).

**Comment by lilixiong2018** [comment]
Good, thank you. very much, maybe you can update README.md to give a note about the usage on Windows.
