### ISSUE TITLE
Removing duplicate lines

### ISSUE THREAD

**Issue by sergeevabc** [benhoyt/goawk#33]
Dear @benhoyt, I’m confused right from the start because

```
awk "!line[$0]++" wordlist.txt > deduplicated.txt
```
works as expected whereas 
```
goawk "!line[$0]++" wordlist.txt > deduplicated.txt     
----------------------------------------------------            
!line[$0]++                                                     
         ^                                                      
----------------------------------------------------            
parse error at 1:10: expected lvalue before ++ or --            
```
throws aforementioned error. What would you recommend to do here?

**Comment by benhoyt** [comment]
This looks like a legit bug, thank you! I'm very surprised I hadn't noticed this before, as GoAWK has a pretty thorough suite of tests (taken from the `awk` and `gawk` test suites). I'll look into this in the next couple of weeks.

**Comment by benhoyt** [comment]
If you need a workaround in the meantime you can parenthesize the `line[$0]++` expression:

```
goawk "!(line[$0]++)" wordlist.txt > deduplicated.txt
```

**Comment by benhoyt** [comment]
Thanks for the bug report! Fixed and released https://github.com/benhoyt/goawk/releases/tag/v1.6.1. Can't believe it's been like this since v1.0.0 and hadn't been caught yet. :-)

There was actually a GAWK test for a similar case, but I had it in my "skipped" bucket because I thought it was due to another issue. There's a known issue with parsing double-dollar expressions like `$$a++++` -- I'm going to take a closer look at that and see about fixing that one too.

**Comment by sergeevabc** [comment]
Err… Ben, 1.6.1 sources are present, but binaries are missing.

**Comment by benhoyt** [comment]
Aha, oops, will fix tomorrow.

**Comment by benhoyt** [comment]
Uploaded!

**Comment by sergeevabc** [comment]
Dear @benhoyt, I’ve just stumbled upon ~400 KiB size difference after de-duplication of 6 MiB text file via GoAWK and original AWK. The difference is explained by line endings used (Windows vs UNIX). Is there a way to use UNIX line endings for consistency?

**Comment by benhoyt** [comment]
Hi @sergeevabc Thanks. Can you please provide a sample script and inputs that reproduce this problem? Do you think this is a goawk-specific issue, or it has more to do with your line ending differences, and you'd just like goawk to normalize it? (Does awk/gawk have the same issue?)

**Comment by sergeevabc** [comment]
[list-20210221-01.7z][1]

```console
$ awk "!a[$0]++" list-original.txt > list-awk.txt
$ goawk "!a[$0]++" list-original.txt > list-goawk.txt

$ wc -c list*
6404594 list-awk.txt     
6759614 list-goawk.txt   
6404594 list-original.txt

$ xxhsum list*  
2d1d8df78c47530b  list-awk.txt                                                                 
717435dbe29ff67d  list-goawk.txt                                                               
2d1d8df78c47530b  list-original.txt                                                            

$ diff --brief --report-identical-files list-awk.txt list-original.txt
Files list-awk.txt and list-original.txt are identical

$ diff --brief --report-identical-files list-goawk.txt list-original.txt
Files list-goawk.txt and list-original.txt differ                                                                             

$ diff --brief --report-identical-files --strip-trailing-cr list-goawk.txt list-original.txt 
Files list-goawk.txt and list-original.txt are identical                                                                      
````

[1]: https://siasky.net/_AnZkuRGakBDFeQd4WNLBw_ER3l_VsNZDsaEkhx75ao8zQ

**Comment by benhoyt** [comment]
Thanks @sergeevabc. I removed your attachment because it was a list of porn domains, and I'd prefer that not linked to here. Next time it'd be best to attach a minimal example which reproduces the problem -- in this case I think just a couple of lines with only LF (`\n`) line endings would suffice.

It looks like you're running on Windows, but awk and gawk on Linux have a similar problem -- Gawk seems to keep the file's existing line endings, whereas GoAWK outputs the platform's line endings. I'm not sure which is better, or which is correct!

Here's a minimal repro script on Linux:

```
$ python3
>>> f = open('t.txt', 'wb')
>>> f.write(b'one\r\ntwo\r\n')
10
>>> f.close()
>>> 
$ hexdump -C t.txt 
00000000  6f 6e 65 0d 0a 74 77 6f  0d 0a                    |one..two..|
0000000a
$ awk '!a[$0]++' t.txt | hexdump -C
00000000  6f 6e 65 0d 0a 74 77 6f  0d 0a                    |one..two..|
0000000a
$ goawk '!a[$0]++' t.txt | hexdump -C
00000000  6f 6e 65 0a 74 77 6f 0a                           |one.two.|
00000008
$ awk --version
GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)
...
$ goawk --version
v1.6.1
```

In addition, as you can see below, Gawk seems to include the CR (`\r`) character of the line ending in the last field (field `$2` below). This seems non-ideal:

```
$ awk '{ printf "%s_%s/", $1, $2 }' t.txt | hexdump -C
00000000  31 5f 6f 6e 65 0d 2f 32  5f 74 77 6f 0d 2f        |1_one./2_two./|
0000000e
$ goawk '{ printf "%s_%s/", $1, $2 }' t.txt | hexdump -C
00000000  31 5f 6f 6e 65 2f 32 5f  74 77 6f 2f              |1_one/2_two/|
0000000c
```

I gather you're running on Windows given the double quotes used as escape character on the command line? Also, can you send the version of `awk` and `goawk` that you're running?

@arnoldrobbins do you have any comment about this, or links to documentation/discussion about this issue?

**Comment by arnoldrobbins** [comment]
Gawk is consistent . RS has the default value of \n and that is what terminates records. As far as gawk is concerned, the \r is  no different from any other character, which is why it appears as part of the last field in the record.

That said, on Windows, I believe the default is to work in text mode, in which case gawk never sees the \r\n line ending, it only sees \n.  One can use BINMODE to force gawk to see those characters, in which case you would need to set RS = "\r?\n" in order to get correct processing.

Take the Windows advice with a grain of salt. I have not used a Windows system directly in over two years, and when I did I used Cygwin, so some experimentation may be in order.

If one is processing a Windows file on Linux, then one should use a utility like `dos2unix` on the file, or `tr`, before sending the data to GoAwk, which does not (yet! hint, hint) allow RS to be a regular expression.  Using GoAwk on Windows, well, you'll have to figure out what the Go runtime is handing off to your code.

Hope this helps.
