### ISSUE TITLE
Reconsider handling of bytes vs characters in length() and similar functions

### ISSUE THREAD

**Issue by benhoyt** [benhoyt/goawk#35]
Per @arnoldrobbins comment https://github.com/rmyorston/busybox-w32/issues/174#issuecomment-599194834, the POSIX spec says that `length` and similar functions should work with characters, not bytes. The [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html) says:

> The index, length, match, and substr functions should not be confused with similar functions in the ISO C standard; the awk versions deal with characters, while the ISO C standard deals with bytes.

Given that, I wonder why (onetrueawk) `awk`'s `length()` function counts bytes instead of characters, at least by default. Here's output on my macOS Catalina machine:

```
$ echo 絵 | nawk '{print length}'    # onetrueawk/awk 20200228
3
$ echo 絵 | gawk '{print length}'    # gawk 5.0.1
1
$ echo 絵 | mawk '{print length}'    # mawk 1.3.4 2020012
3
$ echo 絵 | goawk '{print length}'    # goawk 1.6.0
3

# for reference:
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

So I feel good that GoAWK has the majority on its side :-), but as you point out, the `nawk/mawk/goawk/ behavior does seem wrong according to POSIX. What do you recommend, @arnoldrobbins?

**Comment by arnoldrobbins** [comment]
You ask:
> I wonder why (onetrueawk) awk's length() function counts bytes instead of characters

The answer is that onetrueawk is not POSIX compliant, at least in this regard. Check out the last entry in the BUGS section of its man page, which states that it only supports eight-bit characters. A similar consideration applies to mawk.

I recommend that goawk be POSIX compliant and work with characters, not bytes. In the worst case, you may also wish to adopt gawk's -b option, although I don't know that I actively recommend that.

Hope this helps.

**Comment by benhoyt** [comment]
I've been thinking on and off about the best way to implement this. There will be a significant performance penalty for those functions (`index`, `length`, `match`, and `substr`): because Go/GoAWK stores AWK strings as UTF-8 encoded Go strings, those functions will have to do counting / UTF-8 decoding, rather than just returning a byte index or using a string slice operation in the case of `substr`. So several of those operations that are currently O(1) will become O(N) in the length of the string.

Given the performance penalty (and the fact that this will be a backwards-incompatible change), I think it should be opt-in. So I could make it a compile-time option (Go build tag) to switch from bytes to characters. Or it could be a `Config.UseChars` or similar runtime configuration option, and include the code to do it both ways. I think I'm leaning towards the latter, a runtime config option. (We'll probably want a way for the `goawk` binary to use both, and perhaps even use character by default with the `goawk -b` option as Arnold suggests.)

**Comment by arnoldrobbins** [comment]
Hi. I am afraid that I disagree with you. 

Firstly, POSIX compatibility in this day and age wins out over backwards compatibility. Users of Asian languages (for example) expect these functions to work on characters. 

Secondly, I firmly believe that awk programs are I/O bound, and the "performance penalty" you are worried about in practice is down in the noise where it can barely be measured, if at all.

Gawk has been multibyte compatible for well over a decade, and no one has complained about performance issues related to these functions.

You do want to be careful when looking for \n to separate records and whitespace to separate fields to use byte operations and not wide characters.

Feel free to discuss with me more in private email, or on Github if you really want.

**Comment by benhoyt** [comment]
@arnoldrobbins Yeah, on further thought I think that's fair enough. It shouldn't break many scripts, as you'd have to use constant indexes in substr() *and* have non-ASCII input for the parts you're substr()ing. My guess is that most usages either pass indexes from index/substr/match to substr (non-constant) or have known ASCII inputs for the parts they're substr()ing.

For Go usage, I'm going to make this a runtime config setting (Config.Bytes), which will default to false, i.e., default to character mode. I've also added a `-b` option to the `goawk` command, ala Gawk. Code at https://github.com/benhoyt/goawk/pull/83.

**Comment by benhoyt** [comment]
Reopening this as I've unfortunately had to revert the above fix, due to its problematic O(N) behavior, which made certain scripts O(N^2) and untenably slow. To fix properly, we'll need to come up with a more clever scheme than counting characters when the functions are called.

I wonder, does Gawk store strings as 32-bit runes (in default, non-bytes mode)?

**Comment by arnoldrobbins** [comment]
Gawk goes to a lot of work to make string handling efficient. First, strings are reference counted, to avoid lots of copying.  Next, gawk caches the value of MB_CUR_MAX since (at least on glibc) that macro hides a function call, but the value won't change within a single execution.

Strings themselves consist of the reference count, some flag bits, a (char *, size_t) pair for the original (likely encoded) data, and a (wchar_t, size_t) pair for "runes". The size_t is the length, since gawk allows embedded zero characters in strings.

If in a single-byte environment (MB_CUR_MAX is 1) then gawk can be fat, dumb and happy and never convert to wchar_t.  Otherwise, as soon as the wchar_t version of a string is needed (*but not before*), gawk does the conversion.  From then on, it uses the wchar_t version if it's needed subsequently.

HTH.

**Comment by benhoyt** [comment]
@arnoldrobbins Thanks, that's very helpful. I figured Gawk would be a lot smarter about this. I could definitely do something similar in Go (though as you indicate, it does introduce a fair bit of complexity).

Does Gawk also store (alongside the string) whether a particularly has any non-ASCII characters in it? So that it can skip creating the wchar_t version in those cases?

**Comment by arnoldrobbins** [comment]
In answer to your last question, gawk doesn't store a flag for a string being ASCII / non-ASCII. The decision is based exclusively on MB_CUR_MAX being == 1 or > 1.  In the latter case, when it needs to, it does the conversion and then works on the wchar_t representation for `length()` et al.

**Comment by n8ta** [comment]
One other issue with using characters instead of bytes is that it's not clear what the length of a string is if it's not a valid string in your locale. For instead if we were using UTF8:
```
BEGIN { a = "\000abc"; print length(a)  }
```
The null byte shouldn't exist in a utf8 string. 

Or even worse what if we truncate a two byte codepoint?
```
BEGIN { a = "\306\222"; print a; print length(a)  }
```
Should clearly print this for the 2 byte ƒ char 
```
ƒ
1
```
But if we chop it up?
```
BEGIN { a = "\306"; print a; print length(a)  }
```

Gawk is polite enough to warn you "Invalid multibyte data detected. There may be a mismatch between your data and your locale." but it's not that there is a defined length here. Struggling this with my own awk at the moment. @benhoyt or @arnoldrobbins if you find a satisfying answer please share (:

**Comment by benhoyt** [comment]
Yeah, this is interesting. I definitely don't have a satisfying answer -- GoAWK is still mostly bytes-oriented. Out of interest, is [rawk](https://github.com/n8ta/jawk/tree/main/rawk) your awk (Rust + AWK)?

**Comment by arnoldrobbins** [comment]
Hi. W.R.T. a spec, you should send an interpretation request to the POSIX people.  The gawk code is in `node.c` in `str2wstr()`.  Basically, if gawk knows it's in a Unicode locale, it converts invalid bytes to `0xFFFD` (or whatever is the "invalid character" code in Unicode).  Otherwise it just drops the byte and keeps going.   So for Unicode, at least, the length isn't off, even if the contents differ somewhat.

Almost any way to handle this kind of case will have different tradeoffs; I think what gawk does is reasonable, but maybe someone else would make a different decision.

@n8ta, I took a quick look at your project. Be aware that mawk's regex matcher may be fast, but it's limited to byte matching; you'll need another option if you really want to support Unicode.  Also, I hope that having `ARGV` be read-only is only temporary.  In any case, good luck w/your project!

**Comment by datatraveller1** [comment]
Hi, is there news about this issue?

`print length("Céline")`
still returns 7 instead of 6

I use GoAWK under MS Windows. The file is UTF-8 encoded (as far as I understand it, GOAWK only works with UTF-8 encoded files). The project is great (thanks for that), but unfortunately I can only use it to a very limited extent because of this problem.

**Comment by benhoyt** [comment]
Hi @datatraveller1, unfortunately no news -- at least in my own usage (and many other usages I've seen), this distinction has never been important, because you're almost always using the result of `length` or `RSTART` as an input to `substr`, rather than hard-coded lengths. As a result -- and because doing a fast implementation is hard! -- I've deprioritised this.

However, I'm very interested to see what your use case is in context. Are you able to share the context, or your full AWK script with some notes on what it's doing? We may be able to at least find a workaround.

**Comment by arnoldrobbins** [comment]
@benhoyt I think you're making a premature optimization. Awk programs in general are I/O bound, and the cost of computing things like byte lengths vs. character lengths and conversion back and forth should be down in the noise. I suspect that if you profile, you'll find this to be true.

In general, users expect their programs to follow the standards and it's a multibyte world today.   Go is pretty good about byte to character conversions, you shouldn't have to do a lot of the work manually the way gawk does.

**Comment by benhoyt** [comment]
@arnoldrobbins Two things:

1) I/O used to be the bottleneck, but in the last decade or two that's no longer the case ([more in my article here](https://benhoyt.com/writings/io-is-no-longer-the-bottleneck/)). Sequential read speed is fast, especially on SSD drives -- and normally the processing you're doing can't keep up with the disk.

I just ran my [count-words program](https://github.com/benhoyt/countwords/blob/c66dd01d868aa83dc30a9c95226575df1e5e1c5a/simple.awk) under GoAWK with the profiler turned on, and less than 2% of the time was spent in OS read calls (and that's after flushing the read cache using `sudo /sbin/sysctl -w vm.drop_caches=3`). Here's a screenshot of the profile graph -- you can see only 1.75% on the very left is in `File.Read`, all the rest is map accesses, interpreter stack handling, converting to lowercase, and parsing fields ... the typical stuff AWK programs need to do.

![Screenshot from 2024-03-11 08-28-09](https://github.com/benhoyt/goawk/assets/999033/b4d350e1-d55b-47b9-8e8f-0360a70221a5)

2) If you go back on the thread above, I did actually implement this the simple way (in #83), but that meant `length` and `substr` and similar functions went from O(1) to O(N), which meant that scripts that were using those in a loop went from O(N) to O(N^2), in other words, caused "accidentally quadratic" behaviour in real scripts, such as that described in #93 ... running time went from 1 second to 8 minutes in a test case that wasn't even that large!

To keep `length` and `substr` O(1), I'd need to decode the UTF-8 input into codepoints (characters) up front, which is a cost I'm not sure I want everyone to pay. But I haven't benchmarked that approach yet.

So I think there's three possible ways forward for GoAWK:

1) Go back to the approach above, and tell people whose scripts get the quadratic behaviour to get over it. I don't think this is reasonable, given the "1 second to 8 minutes" example above.
2) Decode UTF-8 to codepoints always on the way in. This would mean I can no longer use Go string functions for most things, and would slow everything down a bunch, but at least `length` and `substr` and friends would remain O(1).
3) Come up with some complicated string representation that makes things fast and O(1). For example, when reading input, mark whether all the bytes in the a string are ASCII and use normal strings, otherwise mark the string as non-ASCII, and lazily decode it from UTF-8 to characters only if you need to. This is a lot of work.

Overall, I still would like to do this, but I'm not sure the trade-offs are worth it given how infrequently it's a problem in practice. As I mentioned above, I'm almost always using the result of `length` or `RSTART` as an input to `substr`, rather than hard-coded lengths, so as long as everything's UTF-8, Unicode handling works just fine. From that PoV, I'd still love to see @datatraveller1's use case or other non-contrived use cases where that's not true.

**Comment by datatraveller1** [comment]
Hi @benhoyt and Arnold, thank you very much for your answers.
It was difficult to create a simple example because the script is complex (the actual script uses fixed length input files) and the extracted, simplified part doesn't seem to make sense, but here it is:

file input.txt with one line content (please note the typo):
**Céline Doin in concert**

```
# script change.awk:
function replace_substring(string, substr_pos, substr_length, replace_with) {
  return substr(string,1,substr_pos-1) replace_with substr(string,substr_pos+substr_length)
}

{
  replacement = "Dion"
  line = replace_substring($0, 8, 4, replacement)
  print line > "output.txt"
}
```
With GAWK and SET LC_ALL=en_US.UTF-8 the result is correct:
`gawk -f change.awk input.txt`
=> output.txt with content
**Céline Dion in concert**
With GOAWK the result is wrong:
`goawk -f change.awk input.txt`
=> output.txt with content
**CélineDionn in concert**

**Comment by benhoyt** [comment]
Hi @datatraveller1, thanks for that. Maybe I need to see more context, but it's the hard-coded constants like 8 and 4 that I don't understand, and tend not to use in my own scripts. For example, if I wanted to replace `Doin` with `Dion`, I'd use `sub` or similar:

```
awk '{ sub("Doin", "Dion"); print }' input.txt

# or, if you just want to look at the second field ("last name")
awk '{ sub("Doin", "Dion", $2); print }' input.txt
```

That way there are no magic constants involved. Perhaps you can include a bit more context to show why your script requires those?

All that said, I would like to make this happen, it's just that it's tricky (as noted in my previous long comment).

**Comment by datatraveller1** [comment]
Hi @benhoyt thank you very much.

The problem is that I often have fixed length fields and use constructs like:
`LINES[NR] = replace_substring(LINES[NR], 41, 120, sprintf("%-120.120s", title))`

I know about sub and gsub and sure there may be workarounds, but it would be nicer if the user could rely on proper multibyte handling for length and substr etc.

I don't know Go, but I wonder if there are native Go UTF-8 string functions that could be used for GoAWK so that the multibyte tasks could be implemented a bit more easily?

**Comment by benhoyt** [comment]
@datatraveller1 Understood, and fair enough if you're using fixed-length fields.

There are straight-forward UTF-8 string functions in Go to do all this, and I've done it before (see above), but the change in performance from O(1) to O(n) for these operations wasn't great, so I reverted it.

**Comment by arnoldrobbins** [comment]
@benhoyt I think you have to go with a simplified version of option (3) from earlier, which is keep both the `[]byte` and `string` representation and a flag saying whether or not the `string` version is valid.  You convert from `[]byte` to `string` lazily, that is, only when you need it.  This is how gawk works.  At least Go does most of the conversion work for you.

Although I understand the desire to be performant, I think that correctness should trump performance.  My two cents, of course. And, as always, the gawk code is available for seeing how I did it and I'm happy to answer questions, privately or in a public forum.

**Comment by janxkoci** [comment]
I wonder what @johnkerl does in [miller](https://github.com/johnkerl/miller) (a modernized unix-like toolkit writen in Go). His awk-like DSL supports Unicode, functions work with chars, and even though it's generally a bit slower than awk, I never seen any quadratic slowdowns there (although majority of my data are from science software and ASCII-only).

**Comment by benhoyt** [comment]
Yeah, it looks like Miller handles this properly as runes (characters) rather than bytes. See its [strlen](https://github.com/johnkerl/miller/blob/9bac6b441314f0d063e9f257e0dddd94a976d913/pkg/bifs/strings.go#L19) function and the other string functions below.

**Comment by benhoyt** [comment]
I'm closing this given that opt-in support for this now exists in the recently-released [v1.29.0](https://github.com/benhoyt/goawk/releases/tag/v1.29.0). I realise not everyone will agree with it being opt-in rather than on by default (POSIX spec included), but given the slowdown of `length()` and similar function from O(1) from O(N) in chars mode, this will have to do for now, and I think this pragmatic solution should serve most people well.

Later, if we come up with a clever way to handle strings that doesn't slow everything else down, we can open a new issue.

**Comment by triallax** [comment]
I've been working on [adding proper character support using libc's wide character functionality](https://codeberg.org/triallax/phos/pulls/119) to [my own awk](https://codeberg.org/triallax/phos), and I thought I can maybe chime in with my empirical observations here.

Initially I did the same thing that goawk does when passed `-u` ("byte strings" are converted to wide character strings on demand with no caching), and I ran into the same performance issues described in this issue (e.g. gron.awk becoming "accidentally quadratic" and taking ages to run). Once I implemented caching for the converted wide strings, performance became much more acceptable (albeit still with an unfortunate slowdown). Here are some benchmarks of this improved version compared to my awk without multibyte functionality at all:
<details>
<summary>benchmark results</summary>

```
Benchmark 1 (10 runs): ./awk-prev -f ../gron.awk/gron.awk ../gron.awk/test_data/big.json
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           509ms ± 6.02ms     501ms …  519ms          0 ( 0%)        0%
  peak_rss           15.1MB ± 85.9KB    15.0MB … 15.2MB          0 ( 0%)        0%
  cpu_cycles         2.05G  ± 19.5M     2.01G  … 2.08G           0 ( 0%)        0%
  instructions       4.33G  ±  182K     4.33G  … 4.33G           0 ( 0%)        0%
  cache_references   3.36M  ±  103K     3.19M  … 3.49M           0 ( 0%)        0%
  cache_misses        729K  ± 75.6K      638K  …  862K           0 ( 0%)        0%
  branch_misses      2.91M  ± 56.5K     2.81M  … 3.02M           0 ( 0%)        0%
Benchmark 2 (8 runs): ./awk-curr -f ../gron.awk/gron.awk ../gron.awk/test_data/big.json
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           674ms ± 13.8ms     659ms …  700ms          0 ( 0%)        💩+ 32.3% ±  2.0%
  peak_rss           20.4MB ± 79.4KB    20.3MB … 20.5MB          0 ( 0%)        💩+ 35.5% ±  0.6%
  cpu_cycles         2.70G  ± 37.3M     2.67G  … 2.78G           0 ( 0%)        💩+ 32.1% ±  1.4%
  instructions       5.93G  ±  221K     5.93G  … 5.93G           0 ( 0%)        💩+ 37.0% ±  0.0%
  cache_references   4.43M  ±  361K     4.07M  … 5.05M           0 ( 0%)        💩+ 31.8% ±  7.5%
  cache_misses        966K  ±  168K      793K  … 1.22M           0 ( 0%)        💩+ 32.5% ± 17.2%
  branch_misses      4.23M  ±  137K     4.10M  … 4.53M           0 ( 0%)        💩+ 45.2% ±  3.5%
Benchmark 1 (15 runs): ./awk-prev -f ../JSON.awk/JSON.awk ../gron.awk/test_data/big.json
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           338ms ± 5.27ms     331ms …  352ms          0 ( 0%)        0%
  peak_rss           22.2MB ± 51.1KB    22.0MB … 22.2MB          0 ( 0%)        0%
  cpu_cycles         1.34G  ± 14.1M     1.33G  … 1.39G           1 ( 7%)        0%
  instructions       3.03G  ± 1.59M     3.02G  … 3.03G           0 ( 0%)        0%
  cache_references   41.8M  ±  587K     40.4M  … 42.7M           0 ( 0%)        0%
  cache_misses       1.04M  ± 99.9K      871K  … 1.29M           0 ( 0%)        0%
  branch_misses      3.58M  ± 40.1K     3.52M  … 3.65M           0 ( 0%)        0%
Benchmark 2 (14 runs): ./awk-curr -f ../JSON.awk/JSON.awk ../gron.awk/test_data/big.json
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           364ms ± 3.79ms     358ms …  373ms          0 ( 0%)        💩+  7.5% ±  1.0%
  peak_rss           27.6MB ± 65.2KB    27.5MB … 27.7MB          0 ( 0%)        💩+ 24.6% ±  0.2%
  cpu_cycles         1.42G  ± 7.03M     1.41G  … 1.43G           0 ( 0%)        💩+  5.6% ±  0.6%
  instructions       3.16G  ± 2.11M     3.16G  … 3.17G           0 ( 0%)        💩+  4.5% ±  0.0%
  cache_references   43.0M  ±  636K     42.2M  … 44.2M           0 ( 0%)        💩+  2.8% ±  1.1%
  cache_misses       1.49M  ± 61.9K     1.41M  … 1.60M           0 ( 0%)        💩+ 43.2% ±  6.2%
  branch_misses      3.95M  ± 34.5K     3.89M  … 4.00M           0 ( 0%)        💩+ 10.3% ±  0.8%
Benchmark 1 (3 runs): ./awk-prev -f ../gron.awk/gron.awk groned -u
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          3.99s  ± 47.0ms    3.93s  … 4.02s           0 ( 0%)        0%
  peak_rss           46.5MB ± 77.1KB    46.4MB … 46.6MB          0 ( 0%)        0%
  cpu_cycles         15.7G  ±  129M     15.6G  … 15.8G           0 ( 0%)        0%
  instructions       32.8G  ± 2.37M     32.8G  … 32.8G           0 ( 0%)        0%
  cache_references    107M  ± 1.45M      105M  …  108M           0 ( 0%)        0%
  cache_misses       14.4M  ± 1.45M     13.1M  … 16.0M           0 ( 0%)        0%
  branch_misses      23.6M  ± 1.60M     22.0M  … 25.2M           0 ( 0%)        0%
Benchmark 2 (3 runs): ./awk-curr -f ../gron.awk/gron.awk groned -u
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          6.02s  ±  164ms    5.92s  … 6.21s           0 ( 0%)        💩+ 51.0% ±  6.8%
  peak_rss           62.1MB ± 81.6KB    62.0MB … 62.2MB          0 ( 0%)        💩+ 33.5% ±  0.4%
  cpu_cycles         23.7G  ±  462M     23.4G  … 24.2G           0 ( 0%)        💩+ 50.8% ±  4.9%
  instructions       51.2G  ±  247K     51.2G  … 51.2G           0 ( 0%)        💩+ 56.2% ±  0.0%
  cache_references    121M  ± 1.46M      119M  …  122M           0 ( 0%)        💩+ 12.6% ±  3.1%
  cache_misses       22.0M  ± 7.51M     14.7M  … 29.7M           0 ( 0%)          + 52.7% ± 85.2%
  branch_misses      53.8M  ±  378K     53.3M  … 54.0M           0 ( 0%)        💩+128.3% ± 11.2%
Benchmark 1 (3 runs): ./awk-prev -f ../goawk/testdata/tt.big_complex_program ../goawk/test
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          1.72s  ± 40.4ms    1.69s  … 1.76s           0 ( 0%)        0%
  peak_rss           2.83MB ± 16.6KB    2.81MB … 2.84MB          0 ( 0%)        0%
  cpu_cycles         6.57G  ± 33.4M     6.54G  … 6.61G           0 ( 0%)        0%
  instructions       14.7G  ±  252K     14.7G  … 14.7G           0 ( 0%)        0%
  cache_references   16.3M  ±  786K     15.4M  … 17.0M           0 ( 0%)        0%
  cache_misses       1.34M  ±  300K     1.12M  … 1.68M           0 ( 0%)        0%
  branch_misses      14.0M  ±  364K     13.6M  … 14.4M           0 ( 0%)        0%
Benchmark 2 (3 runs): ./awk-curr -f ../goawk/testdata/tt.big_complex_program ../goawk/test
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          2.23s  ± 26.1ms    2.20s  … 2.25s           0 ( 0%)        💩+ 29.6% ±  4.5%
  peak_rss           2.88MB ± 48.3KB    2.84MB … 2.94MB          0 ( 0%)          +  1.8% ±  2.9%
  cpu_cycles         8.68G  ± 27.5M     8.66G  … 8.71G           0 ( 0%)        💩+ 32.1% ±  1.1%
  instructions       20.1G  ± 6.50M     20.1G  … 20.1G           0 ( 0%)        💩+ 37.2% ±  0.1%
  cache_references   19.2M  ± 2.47M     16.7M  … 21.7M           0 ( 0%)          + 18.0% ± 25.5%
  cache_misses       1.10M  ±  236K      854K  … 1.32M           0 ( 0%)          - 18.0% ± 45.6%
  branch_misses      23.5M  ±  343K     23.2M  … 23.8M           0 ( 0%)        💩+ 68.0% ±  5.7%
```

</details>

(benchmarking program is https://github.com/andrewrk/poop, if anyone's curious)

I'd additionally also had a crack at the optimisation [explained by @arnoldrobbins earlier](https://github.com/benhoyt/goawk/issues/35#issuecomment-1020994304):

> If in a single-byte environment (MB_CUR_MAX is 1) then gawk can be fat, dumb and happy and never convert to wchar_t.

This also brought further performance improvements; for example, the performance in the first benchmark above was only ~15% worse with this optimisation as compared to ~30% without. However, I've reverted it for now because the way I implemented it wasn't quite correct (when `MB_CUR_MAX` is 1, I was incorrectly using Zig's builtin ASCII functions for e.g. uppercasing instead of the libc's locale-aware functions, in this case `toupper`). However, this isn't relevant in goawk's case, given that it would probably be using the Go stdlib for unicode functionality anyway instead of the libc as I am here (which is needed to be strictly POSIX-conformant with regards to e.g. locale support, but likely not worth it for goawk).

For GoAWK, even if `-b` remains the default, I think implementing some version of, at the very least, the caching optimisation would do wonders to make `-u` much faster.  I also believe there may be a case for making `-u` the default if that optimisation, plus maybe some of the others discussed above, are implemented, notwithstanding backwards compatibility concerns that can be discussed later.

@benhoyt I can consider sending a PR to implement caching converted runes on demand, if it's not too difficult; would you be okay with that?

**Comment by benhoyt** [comment]
Hi @triallax, nice work on your Awk in Zig, and this optimisation. Could you describe your wide string caching approach in a bit more detail, and how it'd work in Go? Would you have a `map[string][]rune` cache, and use that for length/substr, index, match? How would you delete old or unused items from the cache to avoid unbounded memory growth?

Arnold's correct that One True Awk now handles Unicode, however, it also has the "accidentally quadratic behaviour", with `length()` and friends now being O(string_length) operations. This is not a problem in most real-world Awk scripts, but it can be in some (like gron.awk), and that's why I'm not comfortable with that as the default for GoAWK.

**Comment by benhoyt** [comment]
Ah, that's interesting, thanks for the clarification. I think that's worth a shot! Feel free to give it a try and push up a PR (I've already got a bunch of benchmarks so it shouldn't be too hard to compare). You can make it as hacky as you want for a draft, to prove out the concept and performance implications, and then if we're happy with the speed and approach we can clean it up after.

I'm curious why it helps so much with gron.awk though ... are length() and similar functions being re-run often on the *same string object*?

We could also play with putting the runes slice directly in the `value` struct, to compare performance of that (my guess is that this would be slightly higher memory usage, but probably faster):

```go
type value struct {
    typ   valueType
    s     string
    runes []rune
    n     float64
}
```

**Comment by triallax** [comment]
> Ah, that's interesting, thanks for the clarification. I think that's worth a shot! Feel free to give it a try and push up a PR (I've already got a bunch of benchmarks so it shouldn't be too hard to compare). You can make it as hacky as you want for a draft, to prove out the concept and performance implications, and then if we're happy with the speed and approach we can clean it up after.

Sure, I'll whip up something soon enough!

> I'm curious why it helps so much with gron.awk though ... are length() and similar functions being re-run often on the same string object?

No idea, can take a look later

> We could also play with putting the runes slice directly in the value struct, to compare performance of that (my guess is that this would be slightly higher memory usage, but probably faster):

This is also an option, but then the `runes` part won't be shared between duplicates of the same value. For example, if the value of a variable that happens to be a string is pushed onto the stack, then `length` called on the stack value, the runes will not be cached for the original global variable value which I suspect will make this optimisation significantly less useful (though of course we can try it anyway!).

**Comment by arnoldrobbins** [comment]
> > We could also play with putting the runes slice directly in the value struct, to compare performance of that (my guess is that this would be slightly higher memory usage, but probably faster):
> 
> This is also an option, but then the `runes` part won't be shared between duplicates of the same value.

Aren't slices reference types? So if you assign from one slice to another, they use the same underlying storage?

I haven't done any Go programming in over 1/2 a year, so I'm a little hazy about some of the specifics.

**Comment by benhoyt** [comment]
Ah no, I don't think I'd ever quite understood what Gawk did or that's what you were suggesting. Seeing @triallax's suggestion helped!

> Aren't slices reference types? So if you assign from one slice to another, they use the same underlying storage?

Yes, that's right (in Go).

**Comment by triallax** [comment]
> This is a nice description of what gawk does. @benhoyt , I guess you never understood that I was suggesting you do something similar ("do it like gawk") in Goawk.

Indeed, my approach was largely inspired by gawk's (albeit a little different in some details).

> Gawk uses flag bits to know (a) the original type of a value: string or number, and (b) if the other type of value is current. It uses another flag bit to know if the wide string value is available or not. Everything sits in one structure (the goshawful NODE struct). These values are reference counted, and pointers are pushed on or popped off the stack.

This is a bit of a digression on my part, but: this bit I do a little bit differently in my implementation. My value type (which I call `Scalar` internally) looks like this (apologies but I won't be translating from Zig anymore, but I think this should hopefully be obvious enough still):
```zig
pub const Scalar = union(enum) { // (note: union(enum) means "tagged union" essentially)
    /// A number value.
    number: f64,
    /// An uninitialized value that can act as both a string or number value
    /// depending on context.
    uninitialized: void,
    /// A non-numeric string value, stored as a reference-counted value.
    string: RcStr,
    /// A (possibly) numeric string value, stored as a reference-counted value.
    numeric_string: RcStr,
};
```
No allocations or reference counting is needed for non-string values, which is pretty nice for memory use, and the type is quite small (only 16 bytes on x86_64). But also, this allows me to use hacky tricks to reduce the size of `Scalar` even further. I actually have a branch [in which I've implemented NaN boxing](https://codeberg.org/triallax/phos/pulls/116), reducing the size further to 8 bytes, which from my benchmarking gives modest but noticeable speed and memory improvements. :D

I've looked a little look at gawk's `NODE` type and I see it stuffs in a lot of information in it and even represents types that I handle completely separately, such as arrays. I follow in goawk's footsteps here and do some basic type analysis before a program runs to determine what's an array and what's a scalar, which allows me to store array and scalar variables separately. (Of course, this entirely precludes implementing true multidimensional arrays, but I'm okay with that since my goal was always POSIX compatibility only)

> Aren't slices reference types? So if you assign from one slice to another, they use the same underlying storage?
>
> I haven't done any Go programming in over 1/2 a year, so I'm a little hazy about some of the specifics.

Slices are indeed reference types in Go, but structs (goawk's value type is a struct) are of course not. And goawk is similar to my awk in that it passes around AWK values "by value", rather than "by reference" as Gawk does. So changing some field in one copy of a value somewhere won't affect the same field in other copies; but using a heap-allocated inner "AWK string" type we can work around this at the relatively minor cost of double pointer indirection to access the true string data.

> @triallax , I'm glad you're pushing this forward in Goawk. Kudos to you.

Thank you, hopefully we'll get some good stuff merged in. :)

**Comment by triallax** [comment]
> at the relatively minor cost of double pointer indirection to access the true string data.

I just got another idea for this, we could do this instead:

```go
type value struct {
    typ   valueType
    s     string
    runes *[]rune
    n     float64
}
```

which makes `value` a little bigger (probably by 8 bytes on 64-bit platforms) but now there's no indirection involved in getting the "byte string" value.

**Comment by benhoyt** [comment]
Ah, I see now why you want `*[]rune` -- so that if you *set* the "runes" slice on one value it'll apply to the others. A normal non-pointer `[]rune` would make copies fine if the slice was already set (for *get*), but not *set*.

However, I think there will be a significant performance hit for this, because it'll mean for any new (string) value, you'll have to preallocate a "box" for the slice value, to set the runes pointer to. In other words, another allocation per value. That said, we won't know till we try!
