### ISSUE TITLE
release arm binaries

### ISSUE THREAD

**Issue by c-nv-s** [benhoyt/goawk#36]
is it possible to release arm6/7 binaries along with the existing ones

**Comment by benhoyt** [comment]
For what operating system? I could release ARM binaries, but there are also a large number of combinations of operating system + architecture, so I stuck with the "top 3". It's very easy to build them yourself, though, due to Go's cross compiling. Just install Go on your host system and type something like:

```
GOOS=linux GOARCH=arm GOARM=7 go build   # to build for ARM7
```

See more here: https://github.com/golang/go/wiki/GoArm
