### ISSUE TITLE
Parsing Begin Statements

### ISSUE THREAD

**Issue by gthd** [benhoyt/goawk#37]
Is there a specific reason why Begin and End statements are parsed with stmtsBrace instead of stmts ? Or in other words why semi-colons in Begin and End statements are chosen to be ignored ? I am asking because one could want to do using pawk something like this "awk 'BEGIN  {temp = 1 ; print "emp"}' ", setting temp to 1 and printing emp. 

Thank you in advance for your time and consideration

**Comment by gthd** [comment]
Nevermind, I found out what I was searching for.

**Comment by benhoyt** [comment]
I can't remember all the details now of why -- but it turned out to be easier that way. However, while it does ignore `;`, what you have works fine:

```
$ ./goawk 'BEGIN {temp = 1 ; print "emp"}'
emp
```

`goawk` actually works without the `;` at all (though awk/gawk don't). This isn't strictly legal grammar for AWK, but `goawk` is a bit more forgiving than awk/gawk:

```
$ ./goawk 'BEGIN {temp = 1 print "emp"}'
emp
$ gawk 'BEGIN {temp = 1 print "emp"}'
gawk: cmd. line:1: BEGIN {temp = 1 print "emp"}
gawk: cmd. line:1:                 ^ syntax error
```
