### ISSUE TITLE
MS Windows build fails since version 1.9.0

### ISSUE THREAD

**Issue by wneunteufl** [benhoyt/goawk#74]
I use the golang IDE under MS Windows and could not compile my projects anymore.
It fails since goawk version 1.9.0 with this error message:

//go:build comment without // +build comment
--> this import line "github.com/benhoyt/goawk/interp"

Werner

**Comment by benhoyt** [comment]
Thanks for the report! This isn't actually a Windows issue, but an issue with Go versions before 1.17 (the latest) due to the missing old-style `+build` constraint in the fuzz tests I added. Fixed in version 1.9.2: https://github.com/benhoyt/goawk/releases/tag/v1.9.2 ... and I also added CI tests on older versions of Go (I support down to 1.13) to catch things like this.
