### ISSUE TITLE
Support for capturing groups in match function

### ISSUE THREAD

**Issue by pstibrany** [benhoyt/goawk#8]
I'm not sure if adding extensions to awk is something you want to do, but I find having support for capturing groups in match useful, so I've added it here: https://github.com/pstibrany/goawk/commit/45fd318ecad5eaa3a0e98c60f40aaf89e29716b8

It is based on Gawk extension (described at https://www.gnu.org/software/gawk/manual/html_node/String-Functions.html), although I didn't do "start" and "length" subscripts described there, as I didn't know how :-)

**Comment by benhoyt** [comment]
Thanks! I'm not going to add this now (I'd like to focus on polish and performance first) but I'm not opposed to including certain gawk features, so I'm going to leave this open for later.

**Comment by benhoyt** [comment]
I've decided I want GoAWK to focus on the POSIX AWK spec and preference `awk`'s behaviour, rather than adding `gawk`-specific features, so I'm closing this. Thanks for the contribution though, and feel free to fork away!

Also, I just published this, for your interest: https://benhoyt.com/writings/goawk/

**Comment by pstibrany** [comment]
Sounds reasonable to me. Thanks for update.
