### ISSUE TITLE
compilation error on Windows

### ISSUE THREAD

**Issue by jftuga** [benhoyt/goawk#9]
C:\GitHub>git clone https://github.com/benhoyt/goawk.git && cd goawk && go version && go build

    Cloning into 'goawk'...
    remote: Counting objects: 1728, done.
    remote: Compressing objects: 100% (238/238), done.
    remote: Total 1728 (delta 212), reused 324 (delta 142), pack-reused 1328
    Receiving objects: 100% (1728/1728), 1.72 MiB | 8.24 MiB/s, done.
    Resolving deltas: 100% (762/762), done.

    go version go1.10.3 windows/amd64

    # _/C_/GitHub/goawk
    .\goawk.go:147:13: undefined: interp.Config
    .\goawk.go:160:17: undefined: interp.ExecProgram

**Comment by benhoyt** [comment]
Hmm, this is very strange. I'll try to set up builds on Windows via AppVeyor and see if I can repro. But there's nothing platform-specific in the code. What I think's happening is git or Go has got into a funny state and cached an old version of the `interp` package. Because I see interp.go has defined Config and ExecProgram -- see here: https://github.com/benhoyt/goawk/blob/master/interp/interp.go

Can you try a `go build -a` to force rebuilding packages?

**Comment by benhoyt** [comment]
Excellent, thanks for the update. You've made me think more about Windows though, so I'm adding AppVeyor CI as we speak. :-)

**Comment by jftuga** [comment]
Could you then publish a Windows .exe via GitHub releases? That would be cool.

https://github.com/benhoyt/goawk/releases

**Comment by benhoyt** [comment]
I'll get that set up at some point, thanks. In the meantime: https://ci.appveyor.com/project/benhoyt/goawk/build/artifacts
